name: Clean Docker Cache

on:
  workflow_dispatch:

jobs:
  clean-cache:
    runs-on: ubuntu-latest
    steps:
    - name: List and delete GHA caches
      run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
        gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/caches \
          | jq -r '.actions_caches[].id' \
          | xargs -I % gh api -X DELETE /repos/${{ github.repository }}/actions/caches/%
